/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./components/navbar/index.vue')['default']
    Tabbar: typeof import('./components/tabbar/index.vue')['default']
    TabbarFiexdBg: typeof import('./components/tabbar/fiexdBg.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    USticky: typeof import('uview-pro/components/u-sticky/u-sticky.vue')['default']
    USwiper: typeof import('uview-pro/components/u-swiper/u-swiper.vue')['default']
    UTabbar: typeof import('uview-pro/components/u-tabbar/u-tabbar.vue')['default']
  }
}
