/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MyNavbar: typeof import('./components/MyNavbar.vue')['default']
    MyTabbar: typeof import('./components/MyTabbar.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    USwiper: typeof import('uview-pro/components/u-swiper/u-swiper.vue')['default']
    UTabbar: typeof import('uview-pro/components/u-tabbar/u-tabbar.vue')['default']
  }
}
